### ISSUE TITLE
Display of default/ generic image when no home page image is available

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#100]
Since home page images are not a required element in ORPS, there is a chance that publications could be released without. In this case, would it be possible to create a default image to display on the home page/ with the publications in-app?

** Transferred from StatCan Publication: https://github.com/StatCan/StatCanPublication/issues/145 **

**Comment by Jiandong-Guo** [comment]
@Pharste Please provide the default image and its alternative text in both English and French for publication list,
Also do we need display this default image in level 2(webview) ?

**Comment by Jiandong-Guo** [comment]
Seem no need to display default image in level2 because the default image is nothing related to the article content, 
Also the default image is better located to our website(for example the logo image from https://www150.statcan.gc.ca ), just provide us the default image url and Alt text.
If you provide the image data such as png file or jpeg file, we have to save the encoded image data in the app, that increases the app size. so better provide the image url.

**Comment by zhuelle** [comment]
@Pharste would you please provide a status update on this ticket? Thanks!

@payeisa Please provide a priority on this ticket if the business is decided to move forward on this request.

**Comment by Pharste** [comment]
Closing this and moving to ORPS enhancements, to ensure all publications created must have a placeholder image.
