### ISSUE TITLE
French search screen: English subject names in filter menu

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#119]
When viewing the app in French, the filter by subjects list appears![image](https://user-images.githubusercontent.com/89025880/145290117-611dff54-f254-43f2-8e2e-aca1d355d5be.png) in English.

**Comment by ForumG-SC** [comment]
@Pharste The way how it works is , if you search using English word than filter by subject list and all the articles will be displayed in English but if you search a keyword using French word for example "Indices" this keyword is from a article posted in French language, if you search using French keyword than the filter by subject list will be in French not English . The screenshot you provided all the articles are in English because you used English word to search and therefore filter by subjects list is also in English.

**Comment by ForumG-SC** [comment]
@Pharste Could you please validate again and close the ticket ?

**Comment by Pharste** [comment]
Validated, thank you!
