### ISSUE TITLE
For you intro screens - font size

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#121]
The size of the font on the Following and Saved items intro screens should be consistent with the font size used on the Search screen.

For example, the text "Stay informed! Select your subjects of interest to automatically receive the latest info" on the For you/Following screen is smaller than the the text "No results found. Please check your spelling or try again using different keywords." on the Seacrh screen.

![image](https://user-images.githubusercontent.com/89025704/146001743-0206ef10-b3fe-439d-b2fb-64049bc33958.png)

**Comment by ForumG-SC** [comment]
@payeisa Font size on the Following and Saved items intro screens are smaller because  when user switch the language to Francais the text would fit in, if we increase the font size like search screen and switch the language it looks way to off. 

However to make it consistent we can match the search screen's  message size with the for you screen's intro message. Please let me know if you are okay with this solution.

**Comment by payeisa** [comment]
@ForumG-SC Noted, and thank you! I would prefer keeping the fonts as-is in this case, and not change the Search screen's font. If you agree, we can close this ticket. Thanks, Isabelle
