### ISSUE TITLE
Article level 2: Functionality for phone numbers

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#122]
Could we add functionality to the phone numbers in the article level 2 "Contact information" section? Similar to email addresses, when a user selects a phone number, they would be prompted to dial/complete the call.

![image](https://user-images.githubusercontent.com/89025704/146002272-fbc57e01-058c-48ef-87cb-33bd0590c01e.png)

**Comment by Jiandong-Guo** [comment]
@payeisa The information part is coming from article content by calling api, the app is hard to modify it.  The best way is to change it to a link in article content from data source

**Comment by payeisa** [comment]
Thanks for the info @Jiandong-Guo. We can ignore this one for MVP, and add it to Phase 2. Isabelle

**Comment by Jiandong-Guo** [comment]
The information part is coming from article content by calling api,  The best way is to change it to a link in article content from data source(Database)

**Comment by zhuelle** [comment]
@lamokar10 This is a backend issue. Would you please investigate on it and let the mobile dev team know? Thanks!

**Comment by lamokar10** [comment]
@zhuelle @Jiandong-Guo @ForumG-SC @giftydeep 
With regards to the phone numbers and being able to click on it, I am looking at this Daily article : Real-time local business conditions, May 16 to May 22 (https://www150.statcan.gc.ca/n1/daily-quotidien/220527/dq220527e-eng.htm)
1. on the website from my workstation : phone numbers are not "clickable"
2. on the website from my cell phone : phone numbers are clickable
3. on the app : phone numbers are not clickable
4. on the app : click on the Daily link. Phone numbers are not clickable.

Before I contact the ORPS team, I would like to understand why there is a difference from the Daily from a browser and the Daily from the app?

**Comment by Jiandong-Guo** [comment]
@lamokar10 
1) I checked the html code of the contact information section, the code is
<p>For more information, or to enquire about the concepts, methods or data quality of this release, contact us (toll-free <span class="phone">1-800-263-1136</span>; <span class="phone">514-283-8300</span>; <a href="mailto:infostats@statcan.gc.ca">infostats@statcan.gc.ca</a>) or Media Relations (<a href="mailto:statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca">statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca</a>).</p>
the phone number is under a <span> tag with a "phone" class name
2)When you opened it from workstation, the phone number is not clickable, because no javascript code to handle this class. I tested with chrome, it's not clickable, 
3)When you opened it from a browser on your phone, I assume you are using iphone,  it is clickable, I think it's because you are using Safari as the browser, Safari has some default code to handle that class by accident.
4)When I tested it from a browser on my android phone, it is not clickable. because the default browser on android phone is chrome, it is not handling that class.
5) From our app, when you open an article in level 2, our app is using webview to display that article, not using any browser,  the display content is just html string as the data without any javascript code and css style. so no way to make it clickable.
6) From the url you provided, I can see it's from Daily (because it's from www150), all the articles displayed in level 2 in our app are from https://www.statcan.gc.ca/o1/en/api/plus/,   So I think that article is displayed in level 3(we don't have control of level 3 article, at lease for now ).
7) From this example, a new question is raised that is how to handle phone number above level 2.  Will create a new ticket for that situation.

Thanks

**Comment by Jiandong-Guo** [comment]
Hi @lamokar10,
I created a new ticket
   Article level 3 and above: Functionality for handling phone numbers, email, messaging and website #378

so let us focus on article  level2 in this ticket.  What I asked on Apr 26 is to see if the api can return us a link instead of the span. similar like:
![image](https://user-images.githubusercontent.com/58485300/170997530-4be9d972-7330-4692-8b24-62242a7546da.png)

**Comment by Jiandong-Guo** [comment]
If the api cannot return a link for the phone number, please ask the backend team how to specify a number is a phone number since there may be so many numbers in the returned html string.  currently the api returns a plain string like:

For more information, or to enquire about the concepts, methods or data quality of this release, contact us (toll-free 1-800-263-1136; 514-283-8300;

**Comment by payeisa** [comment]
@zhuelle I believe this should be a low priority item (it's tagged as minor)

**Comment by zhuelle** [comment]
@payeisa I have informed Jiandong to not work on the ticket as it is not a priority. He already started look into it and analyzed it but won't continue working on it for now.

**Comment by spotzero** [comment]
@payeisa this needs to be fixed in the content.

To do this, edit the article, and select the phone number, click the "link" button in the editor and set the URL to be: "tel:PHONE_NUMBER".

**Comment by payeisa** [comment]
@weglmar Can you/your team please test this ticket?

**Comment by weglmar** [comment]
Tested in Alpha and using "tel:PHONE_NUMBER" as described works. The app team will begin to ensure phone numbers are formatted this way. 
FYI @payeisa
