### ISSUE TITLE
Explanation for Google

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#178]
**Does not provide ownership information about the news publisher and its contributors, including, but not limited to:**

When applicable, contributors are specified in the Note to readers of the articles. As for ownership in terms of use, Statistics Canada warrants that it is the rightful owner of the app and related documentation that is the subject of this agreement.

**Valid and verifiable contact information/The original publisher of each article** 

All publications added since the last submission should now have valid contact information. As a general rule of thumb, we do not publish the name of specific authors because our business process has all inquiries going through our main points of contact: Infostats or Media Relations. Only in exceptional circumstances do we provide the name of a specific spokesperson.

**Comment by ForumG-SC** [comment]
@Rajat-Sen Please provide updated description limited to 500 characters.

**Comment by ForumG-SC** [comment]
![image](https://user-images.githubusercontent.com/84411852/148578553-f1077eb7-f298-4065-930c-ef98141ae523.png)

**Comment by ForumG-SC** [comment]
Contributors are specified in the Note to readers of the articles. Statistics Canada warrants in terms of use that it is the rightful owner of the content, published in the app.

Contact information is provided under each article. Generally, we do not publish the name of specific authors because our business process has all inquiries going through our main points of contact: Infostats or Media Relations. Only in exceptional circumstances do we provide the name of a specific spokesperson.


Added to the stores, closing the ticket. Thanks
