### ISSUE TITLE
Changing 'social media' page to include website

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#187]
This ticket will be to brainstorm ideas to rename the social media page, and include the website (and possibly other products like the Podcast/My StatCan). @Rajat-Sen @payeisa

**Comment by payeisa** [comment]
Suggestion: 
1) Rename "Social media/Médias sociaux" heading to "Stay connected/Restez branchés"
**this is consistent with what we have on the web: https://www.statcan.gc.ca/en/sc/index

2) Rename the social media section heading from "Connect with Statistics Canada on social media" to "Connect with Statistics Canada / Connectez avec Statistique Canada"

3) Add the following two menu items at the top of the list:
"www.statcan.gc.ca" (links to www.statcan.gc.ca)
Podcasts / Balados (links to https://www.statcan.gc.ca/en/sc/podcasts and https://www.statcan.gc.ca/fr/rb/balados)

@Steph: I would like to look into adding My StatCan after MVP - since it seems to be the "email" version of the app. So I just want to make sure we're not duplicating.

**Comment by payeisa** [comment]
@Pharste @Rajat-Sen Are we ok with the proposed changes?

**Comment by Pharste** [comment]
Yes, I think your suggestion works well!

**Comment by payeisa** [comment]
@Rajat-Sen That sounds great! :)

**Comment by AJBouzidi** [comment]
@Rajat-Sen did you change the design for this? what's the status.

**Comment by AJBouzidi** [comment]
Rajat said @AJBouzidi this is has been update on the UX prototype.

**Comment by ForumG-SC** [comment]
@payeisa The changes as per UX prototype ( https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/779f4dca-1bf6-4508-9e60-011ae713ddca ) has been implemented, please validate in the next release.

**Comment by payeisa** [comment]
Reviewed with changes.
In French, "Site Internet" should be "Site Web", and "Balados" should be "Balado".

**Comment by payeisa** [comment]
@ForumG-SC I will take this ticket back. I'm waiting to get confirmation from the Podcast team, to see if changes will be made to the web page (or not).

**Comment by payeisa** [comment]
@ForumG-SC I received confirmation from the Podcast team. Here are the changes required:

In English, Settings - Stay connected: "Podcast" should be changed to "Podcasts"
![image](https://user-images.githubusercontent.com/89025704/168640691-dab55d2e-72f2-4f5f-a777-38543e8da413.png)

In French, Paramètres - Restez branchés: "Site Internet" should be "Site Web"
![image](https://user-images.githubusercontent.com/89025704/168640573-5a8cb4f0-3573-4872-9507-179da7de77fb.png)

Thanks,
Isabelle

**Comment by payeisa** [comment]
Validated with no issues!
