### ISSUE TITLE
For you / Following "See all" vs "More"

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#194]
@Pharste @Rajat-Sen 

Food for thought...On the "For you/Following" screen (once you follow a subject), the "See all" option is misleading because users can select "See all" to a) see all articles AND to b) unfollow a subject.

Could we consider renaming "See all" to "More" or "More options"?

**Comment by Rajat-Sen** [comment]
Hi Isabelle,

We have two options to choose from as each platform has their own preference.
1. iOS uses "See all"
2. Android uses "See more" or "Right arrow". (Since our app is text focused more, I would recommend See more over an arrow)

The three dots on the top right are referred as "More options". Thus, we cannot use that again as it will confusion from Accessibility point of view.

**Comment by payeisa** [comment]
@Rajat-Sen I think "See more" could work also. 

@Pharste - can you please validate the translation "Voir plus" with ES? (in cases like this, you can simply reach out to them by email). It might be useful to provide a screenshot for reference.

**Comment by Rajat-Sen** [comment]
Sure, let's get it done!

**Comment by Pharste** [comment]
@Rajat-Sen From ES: "See more" is "Afficher plus"

**Comment by ForumG-SC** [comment]
Done

**Comment by payeisa** [comment]
Validated.
