### ISSUE TITLE
Issues with subjects following and "See all" screens

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#195]
I followed the subject "Environment", then clicked on "See all" , and I was presented with the "Agriculture and food" list of articles.
![image](https://user-images.githubusercontent.com/89025704/148703354-7c25c18c-d40e-4cb4-856d-526bd0b29ccb.png)
![image](https://user-images.githubusercontent.com/89025704/148703374-3ce8833a-45df-4054-92d4-c7138e0301d0.png)

**Comment by payeisa** [comment]
If I follow the subject "Housing" and then click "See all", I navigate to the "Construction" screen.

**Comment by spotzero** [comment]
The API is sending the correct list.  The subject you see with the article is the primary subject, the subject you search is either the primary subject, one of the other tagged subject, or is parent subject of the tagged subject. Subjects have an implicit hierarchy.

IE. An article's primary subject is "Agriculture", is it also tagged with "Mental illness".  If you query that you are following "Health", that article will show up, even though it says it's primary subject is "Agriculture", because "Health" is a parent of "Mental illness", so this article is relevant to "Health".

**Comment by payeisa** [comment]
That is in fact the expected behaviour for the search, yes.
However, for the Following screen, we should only display the articles tagged to a primary subject (i.e. same as the Publications screen). Otherwise, this would be confusing for users because we are only giving them to option to follow primary subjects (not secondary). Can we please confirm against the requirements?

**Comment by spotzero** [comment]
Correct me if I'm wrong, but it seems are that there are two options.

Either we update the following API endpoint to only consider only the primary subject, or update the app to display and categorize by the subject being followed instead of the primary subject of the article.

Both are valid, depending on what we think "following a subject" means. At the moment, the primary subject is only used for display, for search, sorting, and categorizing, it's used equally with the other subjects.  However, it's all semantics, these fields can be used however you want.

**Comment by payeisa** [comment]
Thanks Dave - both valid options indeed. We will discuss further tomorrow, and update the ticket after.

**Comment by Jiandong-Guo** [comment]
Also found same thing happens to notifications api, it returns a list with some items subject_id are not belong to requested subject_id.

**Comment by Jiandong-Guo** [comment]
Also found same thing happens to Following api, it returns a list with some items subject_id are not belong to requested subject_id.

**Comment by Rajat-Sen** [comment]
Under a particular subject, if we are seeing articles from secondary subject that's fine. (As we are not displaying the subject on the card itself.) 

But, the title of the screen should be consistent with the subject name if clicked on "See all" under a particular subject.

**Comment by Jiandong-Guo** [comment]
As discussed on the meeting, no change on mobile side, please waiting for the api change and then test again

**Comment by payeisa** [comment]
Will be able to validate once API issue has been resolved.

**Comment by Rajat-Sen** [comment]
Since we are on this page, 

If I start following a subject and change the language and come back to the following screen on my iPad. The subjects that I am following remain in French language.

Needs to be retested once the API issue is resolved. If not, a separate ticket need to be created for this. Thanks!

**Comment by Jiandong-Guo** [comment]
It was validated after the new api release. the title is correct now

**Comment by spotzero** [comment]
The API will only return a 400 Bad Request error when the request the client made is incorrect or invalid JSON.

Server errors will be 500.

**Comment by payeisa** [comment]
Validated my issue. Assigning to @ Rajat to validate his before closing this ticket.

**Comment by Rajat-Sen** [comment]
Validated.
