### ISSUE TITLE
Sorting functionality not working as it should be

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#226]
Will update this shortly!

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo,

Presently, without clicking the sort option on Search screen. How are we sorting the search results initially?

**Comment by Jiandong-Guo** [comment]
The original order is from API, it is descending by published_data automatically

**Comment by goodyke** [comment]
Kerry and Rajat to discuss possible solutions for MVP (keeping in mind the future enhancements desired for the sorting of search results).  This ticket will be updated once the solution for MVP is determined.

**Comment by goodyke** [comment]
The sorting functionality is not working as expected.  Sometimes the user has to click the sort they want to have applied multiple times in order for it to switch the sort and the arrow on the dropdown is confusing.
**Here are the changes that would fix this bug for MVP:**
1. The sorting dropdown should not display the title 'Sort'
2. The sorting dropdown should have a label of 'Sort' (EN) or 'Trier' (FR) **_*instead of putting it in the dropdown_**
3. There should be only two options in the dropdown 'Newest to oldest' and 'Oldest to newest' and the user can _only switch_ from one to the other.
4. The default value in the sorting dropdown should be 'Newest to oldest' and be displayed as such each time a user performs a new search.
5. If the user switches the sort order then the results should always reflect the choice shown in the dropdown
6. The arrow in the dropdown should not be updated based on the sort used... this is simply the arrow that is shown to give the user the tip that the dropdown is clickable (there are other choices)

**Comment by goodyke** [comment]
@Rajat-Sen would you be able to review the comment that I added to this ticket.  If you think that it is clear then please assign this ticket to Jiandong.  Thanks!

**Comment by Jiandong-Guo** [comment]
1)if add a label for sort, better add a label for filter too , to make them nicely align together
2)if change the button label to "Newest to oldest" or "Oldest to newest", the label will be cut-off for small size screen especially in French,  if want to show the whole label, have to make that button a rectangle.  is it looking nice ?
is it still need to show the triangle icon?
3)if the triangle icon stays unchanged,  it is not match with the button label, because the button label will keep changing between "Newest to oldest" and "Oldest to newest",
Please consider these.

my personal view is the current layout is good enough, only one thing needs to change is the triangle icon. currently the triangle icon keeps change everytime user clicks no matter which sub-option chosen, that makes the user confused.  we can improve the triangle icon to match with the sub-option, so if user choose "Newest to oldest", the triangle will be always face-down, and the result will be descending sorted, those 3 all match.  and also the face-down triangle tell the user the result is descending sorted.
if user click "sort" button and choose "Newest to oldest" again, nothing changes.
if user choose "Oldest to newest", the triangle will be face-up, and the result will be ascending sorted. also from the face-up triangle, the user knows the result is ascending sorted

Please think about it

**Comment by goodyke** [comment]
Hi @Jiandong-Guo 
your concerns and suggestions do need to be discussed with the clients.  Please do not work on this ticket for now (until we confirm what _if anything_ will be done during this sprint).
Thanks! Kerry

**Comment by goodyke** [comment]
We discussed this during our review and the solution that was communicated in my comment should be simple (and fulfill the client's priorities).  @Rajat-Sen will add more details to help you understand.

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo, I like your solution but, I would like to add a minor change. Nothing will change in functionality. Give me 15 minutes, you will have the exact design.

**Comment by Jiandong-Guo** [comment]
If fix it following my solution, no need drawing new UX, but fix it following Kerry's solution, better have a draft ux. Thanks

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo, Please find the updated link attached to this message.

When the user searches for the first time, it is searching in the order newest to oldest and we are not going to change anything, we will let it be as it is. I just added a checkmark next to it to show the option was already implemented.

Thus, the only other option the user is left with is oldest to newest and when the user selects that move the checkmark to that option. 

Link: https://xd.adobe.com/view/ba93d6fc-6df6-445a-b4c0-a31e8c15c6e1-efc0/screen/72f06768-56ec-4c9a-96a1-73459625a844/


Please let me know if you have any questions. Thanks!

**Comment by Jiandong-Guo** [comment]
![image](https://user-images.githubusercontent.com/58485300/150597238-a4e3660d-7dce-45ba-8253-0552c51e12e0.png)

**Comment by goodyke** [comment]
Fantastic fix Rajat and Jiandong! 😊

**Comment by Rajat-Sen** [comment]
Validated!
