### ISSUE TITLE
Bold heading showing as underline in app?

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#233]
In the Canadian Peaks Plus article, a bold subtitle is showing as underlined in the app, and looks like a hyperlink:
![Canadian Peaks App](https://user-images.githubusercontent.com/89025880/149704231-bd33d76f-dff0-4e0d-9ce3-9747f8f2d4ed.jpg)
![Canadian Peeks Alpha](https://user-images.githubusercontent.com/89025880/149704235-b67fd653-7791-4ce7-a609-06423682b19c.jpg)

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo , 

"For Further reading" should not be underlined. Could you take a look into this issue. Thanks!

**Comment by Jiandong-Guo** [comment]
I can see the "For Further reading" is a link from the content returned from api:

<p>Nationally, tourists spent $96.0 billion in 2017. Tourism’s economic contribution varied across the provinces and territories, its share of gross domestic product ranging from 1.4% in Nunavut and Saskatchewan to 3.6% in Yukon. Greeting travellers from around the globe who come to explore Kluane’s impressive landscape, these Canadian peaks will stand prouder than ever tomorrow, representing Canada in celebration of International Mountain Day (December 11, 2021).</p>

<p><a><strong>For further reading</strong></a></p>

<p><a href=\"https://www.pc.gc.ca/en/pn-np/yt/kluane/\">Kluane National Park and Reserve</a></p>

<p><a href=\"https://www150.statcan.gc.ca/n1/daily-quotidien/210429/dq210429b-eng.htm\">Provincial and territorial tourism satellite account, 2017</a></p>

**Comment by Jiandong-Guo** [comment]
![image](https://user-images.githubusercontent.com/58485300/149974273-6ee3ccae-ff43-4f1f-b796-c1171f0aaf35.png)

**Comment by Rajat-Sen** [comment]
@Pharste, Could you please validate that this is not a link when the article was published.

I did look into the article on the website and it is not a link. But, please double-check to make sure. Thanks!

https://www.statcan.gc.ca/o1/en/plus/212-canadian-peaks

**Comment by Pharste** [comment]
Hi, I can confirm it is not a link. The screenshots posted in the ticket are of how it's showing in app vs. How the article is in Alpha (with the bold text and two links underneath)

**Comment by goodyke** [comment]
Hi @Jiandong-Guo,
this ticket is similar to #106 in that we are displaying BOLD text as if it is a hyperlink because we add an underline in the display on the mobile app (in #106 we are displaying ACRONYM content as if it is hyperlinked as it is underlined).
I verified the content and the api and there is no concerns with either.
Here is the api call that I made to Alpha for verification (and highlight the **bold** section that is returned).
// 20220121142719
// https://sdr-daily-alpha.cloud.statcan.ca/o1/en/api/plus/article/414

{
  "id": "414",
  "title": "Canadian peaks",
  "url": "https://sdr-daily-alpha.cloud.statcan.ca/o1/en/plus/414-canadian-peaks",
  "type": "Databyte",
  "published_date": "2021-12-30T11:26:11-0500",
  "summary": "Snow-capped mountains are part of the natural beauty in many parts of the country. Canada’s highest peak is Mount Logan, which reaches 5,959 metres in elevation and is hidden away in the St. Elias Mountains of Yukon.",
  "subject_name": "Travel and tourism",
  "subject_id": "24",
  "new_data": false,
  "branding_image_src": "https://sdr-daily-alpha.cloud.statcan.ca/o1/sites/default/files/2021-12/Canadian%20peaks%20web2%29.PNG",
  "branding_image_alt": "Kluane mountains in Kluane National Park, Yukon, under the clouds.",
  "branding_image": "https://sdr-daily-alpha.cloud.statcan.ca/o1/sites/default/files/2021-12/Canadian%20peaks%20web2%29.PNG",
  "content": [
    "<div class=\"paragraph paragraph--type--layout paragraph--view-mode--full\">\n          \n      </div>",
    "<img src=\"https://sdr-daily-alpha.cloud.statcan.ca/o1/sites/default/files/2021-12/Canadian%20peaks%20web2%29_0.PNG\" width=\"1238\" height=\"692\" loading=\"lazy\" class=\"img-responsive\" alt=\"Kluane mountains in Kluane National Park, Yukon, under the clouds.\"/>",
    "<p>Snow-capped mountains are part of the natural beauty in many parts of the country. Canada’s highest peak is Mount Logan, which reaches 5,959 metres in elevation and is hidden away in the St. Elias Mountains of Yukon. Mount Logan stands alongside 17 of Canada’s 20 highest peaks, all located in Kluane National Park and Reserve, a popular tourist destination in southwestern Yukon.</p>\n\n<p>Nationally, tourists spent $96.0 billion in 2017. Tourism’s economic contribution varied across the provinces and territories, its share of gross domestic product ranging from 1.4% in Nunavut and Saskatchewan to 3.6% in Yukon. Greeting travellers from around the globe who come to explore Kluane’s impressive landscape, these Canadian peaks will stand prouder than ever tomorrow, representing Canada in celebration of International Mountain Day (December 11, 2021).**</p>\n\n<p><a><strong>For further reading</strong></a></p>\n\n<p><**a href=\"https://www.pc.gc.ca/en/pn-np/yt/kluane/\">Kluane National Park and Reserve</a></p>\n\n<p><a href=\"https://www150.statcan.gc.ca/n1/daily-quotidien/210429/dq210429b-eng.htm\">Provincial and territorial tourism satellite account, 2017</a></p>",
    "<section class=\"panel panel-info\"><header class=\"panel-heading\"><h2 class=\"panel-title\"> Contact information </h2></header>\n<div class=\"panel-body\">\n          \n            <div class=\"field field--name-field-highlight field--type-text-long field--label-hidden field--item\"><p>For more information, contact us (toll-free <strong>1-800-263-1136</strong>; <strong>514-283-8300</strong>; <a href=\"mailto:infostats@statcan.gc.ca\" title=\"mailto:infostats@statcan.gc.ca\">infostats@statcan.gc.ca</a>) or Media Relations (<a href=\"mailto:statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca\" title=\"mailto:statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca\">statcan.mediahotline-ligneinfomedias.statcan@statcan.gc.ca</a>).</p></div>\n      \n    </div></section>"
  ]
}

**Comment by goodyke** [comment]
> ![image](https://user-images.githubusercontent.com/58485300/149974273-6ee3ccae-ff43-4f1f-b796-c1171f0aaf35.png)

Jiandong if you look at this example that you gave then you can also see that 'For further reading' is just in bold (it is not set as a hyperlink).  If you have any concerns please let me know.

**Comment by Jiandong-Guo** [comment]
You see the content the api returns:
<p><a><strong>For future reading</strong></a></p>
<p>:  tells it is a seperated paragraph
<a>: tells it is a hyperlink even if the href is not set(empty)
<strong>: tells it is a bold style
all those tags will take effection to the inner-most content: For future reading, actually it is a text tag in html

**Comment by Jiandong-Guo** [comment]
sorry, the github itself is a html, it automatically format the string even in Kerry's paste.
I have to use image:
![image](https://user-images.githubusercontent.com/58485300/150602031-52345741-5b5b-4d95-b272-42e5203d3330.png)
The angle bracket p tells it is a seperated paragraph
the angle bracket a tells it is a hyperlink
the angle bracket strong tells it is bold
 all those brackets are tags which will take effective to the inner-most content: For future reading, actually we call a text tag in html

**Comment by goodyke** [comment]
@Jiandong-Guo if the angle bracket 'a' signifies that it is a hyperlink then why is GitHub formatting it correctly? GitHub shows it automatically as bold but no underline when I pasted the results in this ticket above (but the results that I saw showed the same tagging that you have above) Can you change your code to only treat angle bracket 'a Href =' as a hyperlink?

**Comment by Jiandong-Guo** [comment]
I can not change the tag name, because that involves parsing the content string, for example, there could be many unknown tags inside the "a" tag, What I can do is manually give a style let it not showing underline, but not able to change the tag name or remove tag name which is inside the "a" tag(at least  not able to do it for now, it will take along time to write a parsing function, maybe later, but compare the effort, change api is so easy).  the result after I add style is:
![image](https://user-images.githubusercontent.com/58485300/150651639-a345791c-262a-4831-acba-42cbb715c9e1.png)

**Comment by Jiandong-Guo** [comment]
Please test in next release

**Comment by goodyke** [comment]
@Jiandong-Guo I agree with the solution that you have implemented and I will test with the next release.

In addition, I will speak with Dave on Monday to see if he can remove the 'a' tag in the results of the api (so that only hyperlinks will have an 'a' tag and they will have the actual "a ref" html tags with a target url).

**Comment by Pharste** [comment]
Validated
