### ISSUE TITLE
App crashing iOS

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#243]
Hi Jiandong, the app is crashing for some reason and sometimes I am getting a blank screen.

**Comment by Jiandong-Guo** [comment]
Is that api or offline related ?

**Comment by zhuelle** [comment]
@Jiandong-Guo could this crash caused by some fixes we recently added as it was not seeing before?
@Rajat-Sen, if possible, please provide details/steps to get the crash so Jiandong can further investigate on it.

**Comment by goodyke** [comment]
@Rajat-Sen this ticket remains in triage.  Once we can give Jiandong instructions on how to reproduce this bug then we can assign it to him and move it into this sprint.

**Comment by Rajat-Sen** [comment]
I think the app is crashing due to recent changes made on the settings screen. 

If you go to settings scree, select any sub item and then start going back and forth between the tabs (Publications, Search, For you and Settings); The app will crash.

I have tested this way on multiple devices and it crashes every single time I do this.

Thanks!

**Comment by Jiandong-Guo** [comment]
I didn't find this problem on device and simulator.

Also this ticket was reported 2 days ago, but the setting change was happened yesterday

**Comment by Jiandong-Guo** [comment]
Do you remember which subject you select ? 
I didn't find it on ipad

**Comment by goodyke** [comment]
@Jiandong-Guo I will send you an email now with a video that Rajat prepared.  I also have to reopen this issue as I closed it by mistake when I was trying to append the video (it is too big for GitHub).

**Comment by Jiandong-Guo** [comment]
I followed the video steps and didn't find any problem

**Comment by goodyke** [comment]
@Jiandong-Guo I tested with my iPhone and app version 27 and I can replicate the bug too... I can reproduce this bug anytime by switching between the bottom menu items quickly (and more than once).  Do you have an iOS phone? Can you try that?

**Comment by zhuelle** [comment]
@Jiandong-Guo I tested on my Android phone with app version 27 and I can NOT reproduce the crash. This could be only an iOS issue. I know you has an Android phone not an iPhone. But you can test it on your iPad.  Thanks!

**Comment by Jiandong-Guo** [comment]
I don't have iphone, but I have ipad, and didn't find that problem.
Can you remember step by step you replicate that problem. Thanks

**Comment by Jiandong-Guo** [comment]
on my ipad, it show 1.0.27,  what version number is on you iphone?

**Comment by Rajat-Sen** [comment]
You don't need to have an iPhone or iPad; you can test it on your simulator. 

Yes, it is occurring on version 27. I have tested on my iPad and iPhone. On both the devices, I can see it crashing. The step by step process  is already mentioned on my comment above.

**Comment by Jiandong-Guo** [comment]
Cannot find the crash, just doubt maybe you switch the tab too quickly.
added some code to slow-down the switching tab, please test if there is a improvement

**Comment by Pharste** [comment]
Hi, adding this here but please let me know if I should open a new ticket. We received this feedback from a user last week: 

I would like to submit a bug report for the StatsCan app on iOS 14.3 (iPhone
13 Pro). After some time, when switching between tabs or opening a
publication, the application will crash abruptly.

**Comment by Rajat-Sen** [comment]
Hi Steph, this is the same issue and there will be no need to create a new ticket for this. Thanks!

**Comment by Jiandong-Guo** [comment]
App crash:
Problem: The app will crash if user switching the tab navigator too quickly.
Reason:  (could be)
1)	The react native tab component (github.com/react-navigation/react-navigation/issues/10083)
2)	The api call is made during each time the tab gets focused
Potential Fixes:
•	For the reason 1, we can try upgrading package version or use different tab component
We need re-coding the tab component especial for using a different tab component in an different branch, and push to internal test, it may take 2~3 weeks
•	For the reason 2, we will need to re-design our app workflow, it may take 2~3 months
No matter the result of fix#1, this fix should be conducted for the performance of the app.
This fix will combine and update Chris’s proposal and bring out a new solution, the baseline is to eliminate the api call when getting focus.

Right now we have 7 api calls, most of them need to be re-designed too.
	Publication
	Notification
	Followings summary
	Following list
	Search
	Article
	Subjects

 Basic idea of this solution I can think for now is: (using publication api as example)

 Call publication(startArticleId, count) when Publication screen is created. 
•	Here we will use startArticleId instead of page index for easy using
•	The default count is the maximum 20 articles(same as before:version 1.0) 
•	All the article list is sorted descending by published date in the backend
                                    
Besides of the maximum 20 articles, the api should also return backEndLatestArticleId
                                     
The app will render those articles same as before, also the app will save 
•	backEndLatestArticleId, 
•	the current startArticleId 
•	and the first articleId of the returned list as frontEndLatestArticleId ,   for the first time call, the backEndLatestArticleId  and frontEndLatestArticleId  are equal

The app will not do any api call when the publication screen gets focus again. 
        Only when the user scroll down to the end, then trigger an new api call,
        This time, we will use the  updated startArticleId  (the old one -20)  to call the publication api
         It returns a new list will append and render to the end of the screen list,
         It also return a new backEndLatestArticleId,  the app will compare this new backEndLatestArticleId with the saved frontEndLatestArticleId,
       If not same, the app will make another api call for a list from  new backEndLatestArticleId to saved frontEndLatestArticleId, which is the newly published articles.  
       If same, that means no new published articles so far.
If needed, we can add a pull-down function, which will trigger a refreshed api call(same like the calls for first time)

Please think about this solution and discuss its feasibility.

**Comment by payeisa** [comment]
Just to add, I also tried to replicate on Android and was not able to able (i.e. the app does not crash). Thanks, Isabelle

**Comment by Rajat-Sen** [comment]
I have tested the app on iOS and Android. The app does not crash anymore while switching fast between tabs.

**Comment by Jiandong-Guo** [comment]
should it be closed ?

**Comment by Rajat-Sen** [comment]
The app seems to be stable on iOS, this ticket can be closed.
