### ISSUE TITLE
The following screen display in English when setting is in French

### ISSUE THREAD

**Issue by Jiandong-Guo** [StatCan/StatcanPublicationUAT#255]
Problem:  the following screen is always showing in English, even in French setting.
Reason: The French api returns data is in English 
![image](https://user-images.githubusercontent.com/58485300/150828173-20f3e354-02c6-4da6-81a8-5e9adbb7ea32.png)

**Comment by Rajat-Sen** [comment]
@goodyke, when you will be discussing API issues with Dave, would you be able to mention this? Thanks!

**Comment by goodyke** [comment]
@Jiandong-Guo I have reached out to Dave P-D with your concern.  I can not replicate your 'POST' call because I do not have the development tools to do so (and I might not be able to use them correctly if I did).  However, I have created a Teams chat with you and Dave to inform Dave about the issue.  When you have time could you attach your POST example above to that conversation? I gave Dave an example simple call that I made with only one subject id using /fr and subject id = 34 and I was able to replicate your concern - it returned English content.

**Comment by spotzero** [comment]
Oops, this is me.  I'm caching the result payloads, but not separating by language.  I'll implement a fix.

**Comment by ForumG-SC** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2022-01-26 at 08 49 18](https://user-images.githubusercontent.com/84411852/151174749-c2f75151-9d76-474d-8a25-cc7daac98fcd.png)

Issue is fixed in alpha.

**Comment by goodyke** [comment]
The api concern that was causing this issue has been fixed with the latest deployment of the web services to the Production content (it was deployed at 9:21 am on January 26).  Validated the fix with production using version 29 of the mobile app and this concern is now resolved.  Closing this ticket.
