### ISSUE TITLE
Publication level 2: Error message when tapping on email address

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#257]
From an article (Publication level 2), if I tap on the "Ifostats" or "Media relations" email address, I'm presented with an error message:

**Comment by Rajat-Sen** [comment]
This issue seems to only exist in Android, I tested it on iOS and it seems to be working fine.

On Android, it takes the user to their default mail app and when the user comes back it tries to the app, it gives an error. Please return the user to level-2 article instead of loading the same function again which results in error.

**Comment by Jiandong-Guo** [comment]
fixed, please test it in next release

**Comment by Rajat-Sen** [comment]
Hi Isabelle, I have validated from my end, it seems to be working; assigning it back to you to test on your device as well.

**Comment by payeisa** [comment]
Validated.
