### ISSUE TITLE
For you: Following & secondary subject

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#274]
The For you page is displaying articles tagged to secondary subjects. It should be displaying articles based on primary subjects only.

For example "Flooding and landslides in British Columbia: Measuring the costs"
Primary subject is "International trade"

![image](https://user-images.githubusercontent.com/89025704/151205922-deb03da0-6ddf-4a31-b165-22226540d663.png)

However, it's also showing up under secondary subject "Agriculture and food"

![image](https://user-images.githubusercontent.com/89025704/151206534-3f82510b-f3d2-44d6-a53b-66f30a196474.png)

**Comment by goodyke** [comment]
Hi @payeisa,

The concern you have is not due to a bug with the mobile application (as it is showing articles based on what is returned by the api).  Therefore, we do not need to pass this concern to the mobility team.  In addition, I did specify to the Drupal team how the web services should behave and _**it has been implemented according to those specifications**_.  This is the consistent way that we handle subjects across our website (at least for the most part) so I would like to meet you to explain what is happening before we ask the Drupal team to make changes... as you might decide that we have implemented it correctly once we discuss.  If we want to change the requirements then we can do that but there is no point in giving it to developers to action now as there is no software bug in the application and there is no software bug in the api (aka web service).  The software is doing what was specified to be done.

**Do you have time to meet me to discuss today or would you prefer that I just create a Confluence page for us to discuss this (so that we can come up with an agreed upon next step)? If you decide that you want to change how it is working then the next step would be to give the Drupal team new specifications.  If you decide that you are okay with the original specifications then we can close this ticket.  I have assigned this ticket back to you so that you can give me your preference of meeting about this (or having me create a Confluence page and attach it here).**

**Comment by payeisa** [comment]
@goodyke I unfortunately do have time to discuss this issue today, however, this was discussed a couple weeks ago (I don't recall the ticket #), and I thought the understanding was to use primary. @Rajat-Sen @Pharste perhaps I misunderstood?

**Comment by Pharste** [comment]
> @goodyke I unfortunately do have time to discuss this issue today, however, this was discussed a couple weeks ago (I don't recall the ticket #), and I thought the understanding was to use primary. @Rajat-Sen @Pharste perhaps I misunderstood?

Yes, this was my understanding after we had discussed as well.

**Comment by Rajat-Sen** [comment]
@goodyke, we did discussed this in the meeting with Dave and he said he going to make changes to the API and everything should work smoothly. Please reach out to him. Thanks!

**Comment by goodyke** [comment]
@Rajat-Sen I will reach out to Dave and then talk with the clients about what change he is proposing.  Thanks!

**Comment by payeisa** [comment]
@goodyke Would it be possible to get an update on the status of this ticket? Thanks, Isabelle

**Comment by payeisa** [comment]
Hi, Just following up on this ticket. Would it be possible to get an update on next steps? Thanks, Isabelle
@goodyke @Rajat-Sen

**Comment by Rajat-Sen** [comment]
@payeisa, waiting to hear back! Will update you shortly. Thanks for your patience, Rajat

**Comment by payeisa** [comment]
Thanks @Rajat-Sen !
