### ISSUE TITLE
Notifications screen bug

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#278]
When I tap on a new notification, and then tap the 'Continue reading' link, the web browser is brought up (as expected). 

However, when I close the browser and click back from the publication, I'm brought to the Publications home page and not back to my notifications.

**Comment by goodyke** [comment]
I just re-produced the same concern that Stephanie is reporting with this bug and adding the additional clarification for anyone testing the fix:
Opening an article through the notification list to read it (but not opening any other links while reading that article so not being re-directed to the browser before closing) will return the user to the notification list as expected.
**_HOWEVER_**
Opening an article through the notification list to read it (and then opening any a link from the article that results in the app  opening browser to a website page) will NOT return the user to the notification list as expected.  The user is returned to the Publications screen with the notification list closed.

@Rajat-Sen I am assigning this ticket to you so that you can decide the priority for giving this to the developers

@Pharste and @payeisa - perhaps you can comment here as to if this is an important fix to be made before launch or not (to help Rajat with the prioritization)?

**Comment by payeisa** [comment]
I wouldn't consider this a showstopper if we need to prioritize against other more pressing issue.

**Comment by Pharste** [comment]
Agreed @payeisa. Thank you @goodyke for adding the clarification!

**Comment by AJBouzidi** [comment]
@Jiandong-Guo navigation issue.

**Comment by Jiandong-Guo** [comment]
I think it's fixed long time ago with another ticket, please make sure

**Comment by Pharste** [comment]
Hi tested in this release and it is still navigating back to the publications screen rather than the notifications screen.

**Comment by Jiandong-Guo** [comment]
test steps:
1)Run app, display publication home page ---->2) click bell icon on top-right corner, go to notification list --->3) click one of the list item, open article detail page---->4)click back button  "<" on top-left of the detail page, go back to notification list page, --->5)click the back button  "<" on top-left of the notification list page, go back to the publication home page

**Comment by weglmar** [comment]
Hi @Jiandong-Guo, we are doing the following steps: 

1)Run app, display publication home page ---->
2) click bell icon on top-right corner, go to notification list --->
3) click one of the list item, open article detail page---->
**4) click "continue reading" to open web view ---->
5) click "x" in top left corner to close web view, go back to article detail page ---->
6) click the back button "<" on top-left of the article detail page**

It then goes back to the Publications page. But it should bring us back to the notification list. 

@Pharste

**Comment by Jiandong-Guo** [comment]
Thanks @Pharste for quick classification. Please test it in next release

**Comment by payeisa** [comment]
Validated.
