### ISSUE TITLE
Consistent shadow across all sub-menus

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#294]

**Comment by payeisa** [comment]
Hi - has this ticket been validated?

**Comment by Rajat-Sen** [comment]
It has been validated on iOS devices, would you be able to please validate on Android devices as well?

**Comment by payeisa** [comment]
@Rajat-Sen Yes, I can validate for sure! Can you please include a screenshot of what's expected and assign the ticket to me once done?

**Comment by Rajat-Sen** [comment]
Hi Isabelle, these are the screenshots from iOS. The shadow around the element is subtle and helps differentiate from the background. However, I tested on android I cannot see the shadow. Would you be able to please verify from your end. Thanks!


![image](https://user-images.githubusercontent.com/38566088/153945931-c0c91674-6f55-4fbb-9944-bff459e8e831.png)
![image](https://user-images.githubusercontent.com/38566088/153945953-c7034afc-2226-4d5c-90ed-82abe05fda31.png)

**Comment by payeisa** [comment]
@Rajat-Sen It doesn't look like there's a shadow on these ones:
![image](https://user-images.githubusercontent.com/89025704/154057519-37ce8c60-487b-43dd-b33b-7c6c2d468a96.png)
![image](https://user-images.githubusercontent.com/89025704/154057633-e8ad6950-f5be-48a3-87ad-dd2ba2af8718.png)

Does this one have it?
![image](https://user-images.githubusercontent.com/89025704/154057600-f7c0c213-e3f4-4a9c-9a0a-9bc5a5de680c.png)

**Comment by Rajat-Sen** [comment]
Hi Isabelle, it's been hard to see shadows on Android devices since the very beginning. I will make design changes to make sure it will be seen easily on Android devices as well.

**Comment by Rajat-Sen** [comment]
Hi Ali,

On Android, we can see the shadow on this particular screen. However on rest of the screens, the shadow is not visible. 

On iOS, we are are able to see all the shadows. On this particular Search screen, it is darkest as compared to rest of screens.

I think we are using different values for shadows on different screens. Would you be able to please confirm?

Thanks,
Rajat

**Comment by ForumG-SC** [comment]
@Rajat-Sen  

React native doesn't use CSS, so there is limitation with shadows because android doesn't support them. Third-party libraries for these are usually not very performant since they aren't supported in android itself.

Trying to have shadow color on android is not possible with elevation .Tweaking elevation doesn't helps much ,don't expect it to look identical to design or IOS.

I would suggest to adjust the UX design to avoid these on android.

@AJBouzidi  @payeisa 

However, I tested one of the library which uses svg to create fake shadows on android, but it is not an efficient solution as the menu doesn't overlaps the content and pushes down the content on the publications screen and there are other limitations. Please see the attached screenshot below:
![image](https://user-images.githubusercontent.com/84411852/168614551-0cb8db2c-f4cf-4383-8c76-5f13fbb62774.png)

**Comment by Rajat-Sen** [comment]
@ForumG-SC, Please make it consistent on Search screen sort option with other sub-menus. Thanks! I will update the designs for Android devices.

**Comment by zhuelle** [comment]
@Rajat-Sen I assigned this ticket to you as it seems waiting for your design action.

**Comment by Rajat-Sen** [comment]
@ForumG-SC, does React-native support transparency, one option that can be explored is changing the opacity of the menu items to differentiate from rest of the content in the app?

**Comment by ForumG-SC** [comment]
@Rajat-Sen Hi Rajat, this is how it looks when opacity is implemented:

![Image](https://user-images.githubusercontent.com/84411852/179036171-a84de25d-41c8-4a01-a490-26bedd3d1bfc.png)

**Comment by ForumG-SC** [comment]
@Rajat-Sen Please test in next release.

**Comment by Rajat-Sen** [comment]
![Screenshot_20220815-231356.png](https://user-images.githubusercontent.com/38566088/184790681-1041f80c-0f5e-4f2c-ac88-0043c9ec9b3a.png)
![Screenshot_20220815-231300.png](https://user-images.githubusercontent.com/38566088/184790691-722c1903-42fd-4098-b97d-161ee68afcdd.png)

**Comment by Rajat-Sen** [comment]
On notifications screen, it hasn't been implemented properly.

**Comment by Rajat-Sen** [comment]
Validated!
