### ISSUE TITLE
Back button on Android

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#343]
By pressing the back button on Android device, I am able to go back to Welcome and Terms of use screens.

**Comment by Rajat-Sen** [comment]
https://user-images.githubusercontent.com/38566088/160468253-d8fb4a25-810c-4f80-a3b8-1155012b208b.mp4

**Comment by payeisa** [comment]
@ForumG-SC I am unable to replicate this issue on my Samsung S9. I'm not sure if it's because the issue has been fixed, or if it's because I never had the issue in the first place. This was assigned to business for sign off, however, the issue was reported by Rajat. Would it be possible for IT to validate this issue? Thanks, Isabelle

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Hi Jiandong, since you worked on this ticket last sprint, could you please look into it. Thanks

**Comment by Jiandong-Guo** [comment]
It was fixed already, please test it and close it if it's good

**Comment by payeisa** [comment]
@Jiandong-Guo Please see the comment I added earlier this morning. Thanks, Isabelle

**Comment by AJBouzidi** [comment]
validated and closed.

**Comment by zhuelle** [comment]
@AJBouzidi As discussed in our virtual meeting, please test and sign off on behalf of IT. Thanks!

**Comment by Rajat-Sen** [comment]
I agree, the back button doesn't take the user to Welcome screen anymore. However, it isn't functional anymore as well. 

For an android user, after reaching the publications screen the back button stops responding. Instead it should take the user to the home screen or the last screen used from the device.
