### ISSUE TITLE
EAS Build expo

### ISSUE THREAD

**Issue by zhuelle** [StatCan/StatcanPublicationUAT#416]
https://expo.dev/eas?msclkid=e5bb9b49a56711ecb0ef2b084684c462

Expiry date of classic Build:
https://docs.expo.dev/classic/building-standalone-apps/
January 4th, 2023

Right now, we are using classic Expo build system , if we switch to EAS build system which is more flexible , it supports way more npm packages that have native bits of codes it would resolve our adobe analytics issue as with EAS build using third party modules such as react-native-adobe-analytics is doable as we can include libraries with native code that aren’t part of the Expo standard library.

**Comment by zhuelle** [comment]
@ForumG-SC The business has following questions/concerns regarding EAS VS.  Classic Expo build system: 

- what are the impacts when switching to EAS
-  what are the risks of switching
-  what are the risks of not switching
- what do we gain of switch

Please elaborate a bit on each point. Thanks!

**Comment by ForumG-SC** [comment]
@zhuelle 

There are many technical advantages of switching to EAS build such as:

-- No more automatic publishing before building:
 With classic builds, the default behavior is to automatically publish the app bundle as an update prior to running a build. 

This had some unintended consequences; for example, sometimes developers would run a build and be surprised to learn that their existing app was updated as a side effect.

With EAS Build, expo publish is not run as part of the build process. Instead, the JavaScript bundle is generated locally on EAS Build at build time and directly embedded in the app.

-- One of the amazing thing about switching to EAS build is:

Internal Distribution of the app:

Whenever a developer is working on a new feature for the app, we want to make sure it works the way it was designed.
This usually involves building the app and sharing it with testing team.

There are a few problems on iOS when using TestFlight:
The processing time of your new build can take even as long as 60 minutes.
TestFlight can only have one active build at a time.
TestFlight app needs to be installed on the iPhone/iPad.

EAS Build streamlines the process of building apps for internal usage with Internal Distribution, On iOS, we will need to register all devices (iPhones and iPads) ,once all the devices are registered and we will get a sharable URL for the build (and a QR code). We can open it on any of the registered devices and start testing the app with a single click of the installation button.

We can also further automate your workflows with automatic build submissions. That is, we can tell EAS to submit the app to the appropriate app store on a successful project build.

We would eventually need to switch to EAS build as the classic build system in **expiring** in **January**, if we don't switch to EAS build than we won't be able to perform deployment anymore.

Instead of switching the build system in January, it is advisable to switch it in next sprint so we have ample amount of time to fix if any issues occur. 

Risk level is low and uncertain, even if low level of risk is involved we would still need to switch to EAS build system as classic build system is expiring soon.

EAS build is just more flexible and faster than the classic build, it also reduces the app size which would result in quicker installation of the app on the devices.

We would be only be able to test some of it's advantages once we actually switch to EAS build, get ourselves familiar with it and start using it.

**Comment by zhuelle** [comment]
@ForumG-SC Besides the EAS build option, is there any other options to replace the Classic Expo build? Has the dev team done option analysis to choose EAS build option? Thanks!

**Comment by ForumG-SC** [comment]
@zhuelle Hi Ellen, Migration from classic build to EAS build has been completed for the prod.

I will be doing New sprint's(August) deployment as well to finish off the process, I have created new ticket co-related to this ticket for more details please refer to:
