### ISSUE TITLE
Dark mode: Canada word mark on settings screen

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#42]
Hi,

I noticed that the white copy of the Canada word mark is showing up in the dark mode of the app and looks out of place. Can we please replace this with the black version? ![image](https://user-images.githubusercontent.com/89025880/134714329-188ff579-ffa2-4fff-b1f6-d9c4528f66e6.png)

**Comment by ForumG-SC** [comment]
@Pharste Screenshot has been removed and real image has been implemented. However, we have **not received** proper dark theme's color schemes yet due to which this logo would not be visible much in dark mode.   

The changes will be deployed in the upcoming release, requires validation, assigning it back to you.
