### ISSUE TITLE
SDK 44 is not accepted for build app

### ISSUE THREAD

**Issue by Jiandong-Guo** [StatCan/StatcanPublicationUAT#426]
Who is performing Production deployment should monitor it.

![image](https://user-images.githubusercontent.com/58485300/177590626-0a301f59-6c44-4c9f-a8f2-f0f9d4853040.png)

**Comment by ForumG-SC** [comment]
@Jiandong-Guo Please add expo-analytics-segment 11.1.2 because expo had asked everyone to install that to get rid of this error and I believe that you had removed this package in one of your previous commit. 

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/84411852/178268298-767ecab5-9955-4123-8d9e-24e2f2c88ac8.png">

reference: 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/84411852/178268572-ddaf9c84-50f1-4912-bf2d-3209f92fd376.png">

**Comment by Jiandong-Guo** [comment]
From :https://github.com/expo/expo/issues/17845
![image](https://user-images.githubusercontent.com/58485300/178283695-c448902b-5db9-4c75-8336-08d87ef97018.png)
![image](https://user-images.githubusercontent.com/58485300/178283989-a77e87f5-8954-47d2-afc2-03eb6238f901.png)

My concern:
1)This package will collect user info, if no choice we have to use it, is it allowed by our security rule  ?
2) We don't have such issue before, so that must come up by our package auto upgrading, we don't use this package in our code, it must be used in one of our upgraded dependency's dependency code.   also the upgraded packages give a lot of warning compatible info when run expo start
3) so the auto-upgrading package process should conduct in a separated branch, not directly in master, after tested without issue then merge to master.  it's too risky, remember the UUID issue when upgrading package ?   
I may be wrong, just a concern

**Comment by ForumG-SC** [comment]
> From :[expo/expo#17845](https://github.com/expo/expo/issues/17845) ![image](https://user-images.githubusercontent.com/58485300/178283695-c448902b-5db9-4c75-8336-08d87ef97018.png) ![image](https://user-images.githubusercontent.com/58485300/178283989-a77e87f5-8954-47d2-afc2-03eb6238f901.png)
> 
> My concern: 1)This package will collect user info, if no choice we have to use it, is it allowed by our security rule ? 2) We don't have such issue before, so that must come up by our package auto upgrading, we don't use this package in our code, it must be used in one of our upgraded dependency's dependency code. also the upgraded packages give a lot of warning compatible info when run expo start 3) so the auto-upgrading package process should conduct in a separated branch, not directly in master, after tested without issue then merge to master. it's too risky, remember the UUID issue when upgrading package ? I may be wrong, just a concern

It is not related to the package auto upgrading, this issue was also there last month and it was on Expo' side, they came up with quick fix by adding segment package. They keep on upgrading the things in their sdk. I already created new branch , Auto upgrading packages will now on get affected on separate branch called "UpgradePackages" after tested can be merged to master.

**Comment by zhuelle** [comment]
@Jiandong-Guo Have you read Forum's comments above? should we keep this ticket open and monitor it by who is performing deployment?

**Comment by Jiandong-Guo** [comment]
@zhuelle ,Yes, as discussed yesterday, we keep it open for monitoring in next couple of deployment

**Comment by Jiandong-Guo** [comment]
Warning Message: expo-app-loading is deprecated

**Comment by ForumG-SC** [comment]
@zhuelle This ticket can be closed as we are not using sdk44 anymore, currently we are using expo sdk 55.
