### ISSUE TITLE
Introduce a Subjects of Interest screen in the Onboarding screen

### ISSUE THREAD

**Issue by radwahm** [StatCan/StatcanPublicationUAT#461]
https://confluenceb.statcan.ca/display/SPMA/Feature+1.2+-+Introduce+a+Subjects+of+Interest+screen+in+the+Onboarding+screen

**Comment by weglmar** [comment]
@radwahm Hi Ahmed, there is a scenario missing from this user story. Please assign back to me for sign off when completed. Thanks!

**Comment by radwahm** [comment]
Added missing scenarios.

**Comment by weglmar** [comment]
Signed off Sept 23/22.

**Comment by giftydeep** [comment]
FYI the lazy loading screen is not implemented yet. So, after selecting the subject and clicking next instead of the lazy loading screen it will directly jump to For You screen. Once the lazy loading screen will be implemented, I will update that later.

**Comment by giftydeep** [comment]
@weglmar Can you provide me French translations for "Next" and "What Interests you?"

**Comment by weglmar** [comment]
@giftydeep 

What interests you? > Qu’est-ce qui vous intéresse?
Next > Suivant

**Comment by weglmar** [comment]
Tested on iPhone X, XR and Galaxy A11. 

What subjects interest you? screen is appearing every time the app is opened. The screen should only be appearing once during onboarding. 

The Next button is not responsive upon first click (need to click it a lot of times to trigger a response). 

Subjects in French are not listed in Alphabetical order (they are mirroring the English, and same thing happens if in French switching to English).

**Comment by weglmar** [comment]
The following bug tickets are opened, related to this ticket: 
#502 Subjects not listed in alphabetical order in French - Select subjects button on For You tab and Manage subjects screen

**Comment by zhuelle** [comment]
@weglmar can we close this ticket? #506 has been closed but #502 still open but seems cannot be resolved from the app end.
