### ISSUE TITLE
Changes to the navigation (bottom) bar

### ISSUE THREAD

**Issue by radwahm** [StatCan/StatcanPublicationUAT#465]
https://confluenceb.statcan.ca/display/SPMA/Feature+x.x+-+Changes+to+the+Navigation+Bar

**Comment by weglmar** [comment]
Signed off Sept 20/22.

**Comment by Jiandong-Guo** [comment]
@zhuelle @ForumG-SC @giftydeep: Please discuss how to implement the new enhancements:
1)This ticket is the architecture base, a small change will break the whole app
2)If break this ticket into many small pieces, the app will not make any sense for user to test, also If I merge small piece by small piece into master, It will confuse you because some pieces will make no sense with your code.  
3)This ticket will change code for almost all the screens, some screen will be deleted and some new screen will be created, how to collaborate your code if you working on some ticket.
4)If I make a separated branch for testing, it is almost not possible to merge into master, and your change-set will be lost.

**Comment by Jiandong-Guo** [comment]
Please test in the release 3.0.1

**Comment by Rajat-Sen** [comment]
@Jiandong-Guo, for the Tab bar, on the saved icon while using voice over it is still saying "For you" instead of "Saved". Would you please fix the label for the button? Thanks

**Comment by Rajat-Sen** [comment]
@zhuelle, Created a new ticket and assigned to you.
