### ISSUE TITLE
Sept 13 Release note

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#52]
We are unsure what this refers to, or what he testing tasks should be:

Notifications Screen : More icon menu does not push notifications list, design changes fixed. https://xd.adobe.com/view/06f1d9f5-3100-4957-abe8-fa36941132b6-53a2/screen/bb43ea69-08d9-4447-ad82-439715c82eac/

**Comment by ForumG-SC** [comment]
If you compare the notification list screen to the previous version of the release , the menu was pushing the text down instead of overlapping it (see the screenshot below) , that has been resolved.
![image](https://user-images.githubusercontent.com/84411852/134944495-ce61fa06-aee6-454a-92b2-07a6fa20d399.png)

**Comment by payeisa** [comment]
@ForumG-SC Thanks for the clarification!
@Pharste FYI
