### ISSUE TITLE
StatsCAN v3.0.10: Image headers on Android 

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#559]
*Only appearing on Android* 

The image header for the largest image card is displaying incorrectly. See below. 

![image](https://user-images.githubusercontent.com/98898969/221267170-52f84e3a-295b-4d8e-8704-22f1d25e1baf.png)

Device Type: Android Galaxy A11 
Device Screen Size: 6.4 inches 
Device Screen Resolution: 720x1560 pixels 
Device’s OS version info: One UI 3.1

**Comment by weglmar** [comment]
@payeisa Hi Isabelle, could you please test when you get a chance? 
Thank you!

**Comment by payeisa** [comment]
@weglmar I can confirm that the issue is in fact still there. (I also reported it by email).
Device: Samsung S9
Display setting: light mode
Publications screen, All tab
Issue is only happening on the large cards (so on the images displayed in the "Latest" and " Earlier today" sections
![image](https://user-images.githubusercontent.com/89025704/221276400-73936209-3f5f-4f3e-ba24-424642bbc628.png)

**Comment by payeisa** [comment]
Hi @ForumG-SC, Confirming that the issue no longer applies after uninstalling/re-installing the app. Thanks, Isabelle
