### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#56]
No matter which keywords I use, the search results are the same. I would have expected the "No search results" message for the last two searches performed.

![image](https://user-images.githubusercontent.com/89025704/135834518-5f2f6ae1-53f5-4c6b-b4e8-2872c947c2b5.png)

**Comment by AJBouzidi** [comment]
@payeisa don't be cut on with this search, as you know already this is mock data we simulated search. The search engine not within the mobile app, it's developed in the backend. and because we still waiting to connect to backend we cannot search inside the mock data.  This is only to show the navigation.

**Comment by payeisa** [comment]
Validated.
