### ISSUE TITLE
No content displaying for certain articles

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#71]
***Content of type "Infobyte" is not being picked up. Publications of type "Article" and "Databyte" are ok, but for some reason the content for publications of type "Infobyte" is not recognized. As a workaround for consultations, I will not create publications of type "Infobytes".***

If I select the article "Who invests in Nova Scotia's housing market?", I navigate to a blank screen with a "No Content Found" message.

![image](https://user-images.githubusercontent.com/89025704/141976717-978c2cf9-8a4c-48e5-b624-7e2bb60a8380.png)

The same happens for the following articles:
A First Complete Look at Residential Property Prices (Nov 10)
A glance at robots in the Canadian economy, 1996 to.... (Nov 10)
Canadian tomotoes, from farm to fork (Nov 9)
Alcohol Sales in Canada, 2019/2020 (Nov 9)
Employment characteristics for the oil and gas sector (Nov 9)

**Comment by goodyke** [comment]
I researched this by calling the web service to retrieve the article contents for the articles listed in this ticket.  The problem is not that the Plus article is of type 'Infobyte' - the problem is when an article contains content of type 'infographic'... which is mostly those that the users labelled 'Infobyte' (but not always).  For instance, the Alcohol Sales in Canada, 2019/2020 that was published on November 9th is of type 'Databyte' but has the same problem since the content contains the content type 'Infographic'.  A Jira has been created for the Drupal team to fix this - see DAILY-876.

**Comment by goodyke** [comment]
@payeisa this was caused by the StatsCAN Plus web service not returning the infographics content - this has been fixed by Drupal with DAILY-876 which will be deployed to ALPHA this week.  Please verify that the content for the articles listed above is now showing (once the next version of the mobile app is published).

**Comment by payeisa** [comment]
Validated.
