### ISSUE TITLE
For you screen (following)

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#91]
With November 19 release, not all articles with subjects following are showing up on the page. I followed Health, Government and Travel and Tourism and only see one Government article. ![image](https://user-images.githubusercontent.com/89025880/142663081-9b420fc2-c3c2-4d15-b0d9-8caaf9557406.png)![image](https://user-images.githubusercontent.com/89025880/142663087-fff3066a-cdb2-4030-8365-c980a4b4d365.png)![image](https://user-images.githubusercontent.com/89025880/142663096-811f9146-5ddb-483e-acb8-c9735b35f83b.png)

**Comment by Jiandong-Guo** [comment]
This one is related to the highlights workflow in the backend.
Before we use ...api/highlights to get the highlights from app running every time, this list will be accumulated to max 30 days, after 30 days, it will continue to accumulate but will delete the list whose age is more than 30 days. remember  we don't retrieve this list at once.   so when user choose some subjects in manage subjects setting, the app will search from that 30-day list to find the items which belong to that subject group,  since we are not using highlight anymore and switching to using article list, seems that workflow is not working. we have to re-think the workflow, maybe have to retrieve it everytime

**Comment by ForumG-SC** [comment]
@Pharste Please revalidate this issue in the current version.

**Comment by Pharste** [comment]
Hi, 

I've validated that the subjects are all showing up now after I follow them. However, they are appearing in the order they were followed, and not in alphabetical order: 
![Following 1](https://user-images.githubusercontent.com/89025880/150193120-29bb2ade-9245-48c3-b10d-978879101f4b.png)
![Following 2](https://user-images.githubusercontent.com/89025880/150193165-857885e8-5223-4910-a1b8-8aadd2071417.png)

**Comment by goodyke** [comment]
@Pharste - I will close this ticket as done and create a new one for ordering the display of subjects alphabetically on the Following tab.  I will link that ticket here once created.

**Comment by Jiandong-Guo** [comment]
I think the alphabetical order is for category(subject), how about the articles inside each category ?

**Comment by goodyke** [comment]
Okay we will keep this issue in this ticket (alphabetical ordering of subjects in Following) and not create a new one.
@Jiandong-Guo please ensure the subjects on the Following screen are displayed in alphabetical order and that the actual articles continue to be shown in most recent order.

**Comment by Jiandong-Guo** [comment]
Please test it in next release

**Comment by goodyke** [comment]
Validated... @Pharste please close if you agree that this has been fixed with version 28.

**Comment by Pharste** [comment]
Validated, thank you
